# Generated by Django 2.1.7 on 2019-03-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_drinks',
            field=models.BooleanField(default=True),
        ),
    ]
